language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - python -m pip install --upgrade pip
  - pip install pipenv --upgrade
  - pip install codecov --upgrade
  - pipenv install --dev --skip-lock
script:
  - pipenv run flake8 --ignore=W504 lrtree --count --show-source --max-complexity=15 --max-line-length=120 --statistics
  - pipenv run coverage run --source lrtree/ -m pytest
  - pipenv run coverage xml
build:
  - pipenv run pip install --upgrade keyring keyrings.alt
  - python setup.py build sdist bdist_wheel
  - pipenv run twine check dist/*

after_sucess:
  codecov
